//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stock
    {
        public int BookID { get; set; }

        [Display(Name = "Stock Count")]
        public int StockCount { get; set; }

        [Display(Name = "Length of Loan")]
        public int LoanLength { get; set; }
        public int StockID { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
